version: '3'
services:
  db:
    image: postgres:15-alpine
    volumes:
     - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habits
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dfr"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.5-alpine
    expose:
      - 6379

  app:
    build: .
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate --noinput 
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    image: app
    volumes:
      - ./app/:/app/
    container_name: celery_worker
    env_file: /app/.env
    depends_on:
      - app
    command: celery -A config worker -l INFO

  celery_beat:
    image: app
    volumes:
      - ./app/:/app/
    container_name: celery_beat
    env_file: /app/.env
    depends_on:
      - app
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
